name: Build and Deploy Product Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Product Service
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/ferremas-product-service:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/ferremas-product-service:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        
    - name: Trigger Infrastructure Deployment
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.INFRASTRUCTURE_REPO_TOKEN }}
        repository: ${{ secrets.INFRASTRUCTURE_REPO }}
        event-type: product-service-updated
        client-payload: '{"service": "product-service", "tag": "${{ github.sha }}"}'